#! /usr/bin/env python3
import rospy                    # ROS Python API     - what does it do : it is a python client library for ROS   
import sys                      # System module      - it provides access to some variables used or maintained by the interpreter and to functions that interact strongly with the interpreter
import termios                  # Terminal module    - it provides access to the POSIX terminal control interface
import tty                      # TTY module         - it provides access to the POSIX terminal control interface
from sensor_msgs.msg import JointState # JointState message type

# Global Variables
nodeName      = "ARM_teleop"    # Node Name
joints_name   = ["base", "shoulder", "elbow", "lower_wrist", "upper_wrist", "suction"]           # Joint Names


class teleop:

    def __init__(self):        
    #   rospy.init_node(nodeName, anonymous=True)                                               # Initialize the ROS Node
        self.joint = joints_name[0]       
        self.dir = 'cw'
        self.joint_state_publisher = rospy.Publisher('/joint_states', JointState, queue_size=10)



    def publish_joint_states(self, joint_name, dir):
        
        joint_state_msg = JointState()
        joint_state_msg.name.append(joint_name)
        joint_state_msg.header.stamp = rospy.Time.now()
        self.joint_state_publisher.publish(joint_state_msg)
    
    #---------------------------------------------------------------#
    # Function Name : publish_joint_states()
    # Arguments     : joint_states, dir
    # Description   : publish the joint states to the topic
    #---------------------------------------------------------------#
        

    #---------------------------------------------------------------#
    # Function Name : get_continuous_keypress()
    # Arguments     : None
    # Description   : take continuous keypress as input and move the arm to the specified pose
    #---------------------------------------------------------------#
    def get_continuous_keypress(self):


        original_terminal_settings = termios.tcgetattr(sys.stdin)       # Get the terminal settings
        
        # Print the instructions
        
        padding = " " * 27 
        print (f'{padding}\033[35;1mROBOTIC ARM CONTROLLER\033[0m')
        print("\n")
        padding = " " * 5 
        print (f'{padding}\033[33;1mTo move\033[0m')
        print ("\033[90;1mBase             :\033[0m" , "\033[1;37mpress 1\033[0m")
        print ("\033[90;1mShoulder Joint   :\033[0m" , "\033[1;37mpress 2\033[0m")
        print ("\033[90;1mElbow Joint      :\033[0m",  "\033[1;37mpress 3\033[0m")
        print ("\033[90;1mLower Wrist      :\033[0m",  "\033[1;37mpress 4\033[0m")
        print ("\033[90;1mUpper Wrist      :\033[0m",  "\033[1;37mpress 5\033[0m")
        print ("\033[90;1mSuction          :\033[0m",  "\033[1;37mpress 6\033[0m")
        print("\n\n")
        print ("\033[90;1mClock wise Rotation      :\033[0m",  "\033[1;37mpress w\033[0m")
        print ("\033[90;1mAtiClock wise Rotation   :\033[0m",  "\033[1;37mpress s\033[0m")
        print("\n\n")
        print("\033[91mPress keys (Ctrl + C + Enter to exit):\033[0m")
        print("\n")


       # take input and do the required operation
        try:
            tty.setcbreak(sys.stdin.fileno())

            while not rospy.is_shutdown():
                char = sys.stdin.read(1)
                
                if char and char != '\n':

                    
                    if char == '1'  :                                # Move Base Link with keypress 1
                        self.joint = joints_name[0]     
                        print ("\033[A                                                                                  \033[A")
                        print("Joint Selected : ", self.joint , "    Direction : ", self.dir)

                    if char == '2'  :                                # Move Shoulder Joint with keypress 2
                        self.joint = joints_name[1]
                        print ("\033[A                                                                                  \033[A")
                        print("Joint Selected : ", self.joint , "    Direction : ", self.dir)

                
                    if char == '3'  :                                # Move Elbow Joint with keypress 3
                        self.joint = joints_name[2]
                        print ("\033[A                                                                                  \033[A")
                        print("Joint Selected : ", self.joint , "    Direction : ", self.dir)


                    if char == '4'  :                                # Move Lower Wrist with keypress 4
                        self.joint = joints_name[3]
                        print ("\033[A                                                                                  \033[A")
                        print("Joint Selected : ", self.joint , "    Direction : ", self.dir)


                    if char == '5'  :                                # Move Upper Wrist with keypress 5
                        self.joint = joints_name[4]
                        print ("\033[A                                                                                  \033[A")
                        print("Joint Selected : ", self.joint , "    Direction : ", self.dir)


                    if char == '6'  :                                # Move Upper Wrist with keypress 5
                        self.joint = joints_name[5]
                        print ("\033[A                                                                                  \033[A")
                        print("Joint Selected : ", self.joint , "    Direction : ", self.dir)

                    if char == 'w'  :                                # Move Clockwise with keypress w
                        self.dir = 'cw'
                        print ("\033[A                                                                                  \033[A")
                        print("Joint Selected : ", self.joint , "    Direction : ", self.dir)

                    if char == 's'  :                                # Move AntiClockwise with keypress s
                        self.dir = 'ccw'
                        print ("\033[A                                                                                  \033[A")
                        print("Joint Selected : ", self.joint , "    Direction : ", self.dir)


                    
        except KeyboardInterrupt:
            pass
        finally:
            print("Exiting...")
            termios.tcsetattr(sys.stdin, termios.TCSADRAIN, original_terminal_settings)


if __name__ == "__main__":
    teleopObj = teleop()
    teleopObj.get_continuous_keypress()
