// Generated by gencpp from file ajgar_perception/octomapSrv.msg
// DO NOT EDIT!


#ifndef AJGAR_PERCEPTION_MESSAGE_OCTOMAPSRV_H
#define AJGAR_PERCEPTION_MESSAGE_OCTOMAPSRV_H

#include <ros/service_traits.h>


#include <ajgar_perception/octomapSrvRequest.h>
#include <ajgar_perception/octomapSrvResponse.h>


namespace ajgar_perception
{

struct octomapSrv
{

typedef octomapSrvRequest Request;
typedef octomapSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct octomapSrv
} // namespace ajgar_perception


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ajgar_perception::octomapSrv > {
  static const char* value()
  {
    return "616b90dff5e1a5812063533505c3044e";
  }

  static const char* value(const ::ajgar_perception::octomapSrv&) { return value(); }
};

template<>
struct DataType< ::ajgar_perception::octomapSrv > {
  static const char* value()
  {
    return "ajgar_perception/octomapSrv";
  }

  static const char* value(const ::ajgar_perception::octomapSrv&) { return value(); }
};


// service_traits::MD5Sum< ::ajgar_perception::octomapSrvRequest> should match
// service_traits::MD5Sum< ::ajgar_perception::octomapSrv >
template<>
struct MD5Sum< ::ajgar_perception::octomapSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ajgar_perception::octomapSrv >::value();
  }
  static const char* value(const ::ajgar_perception::octomapSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ajgar_perception::octomapSrvRequest> should match
// service_traits::DataType< ::ajgar_perception::octomapSrv >
template<>
struct DataType< ::ajgar_perception::octomapSrvRequest>
{
  static const char* value()
  {
    return DataType< ::ajgar_perception::octomapSrv >::value();
  }
  static const char* value(const ::ajgar_perception::octomapSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ajgar_perception::octomapSrvResponse> should match
// service_traits::MD5Sum< ::ajgar_perception::octomapSrv >
template<>
struct MD5Sum< ::ajgar_perception::octomapSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ajgar_perception::octomapSrv >::value();
  }
  static const char* value(const ::ajgar_perception::octomapSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ajgar_perception::octomapSrvResponse> should match
// service_traits::DataType< ::ajgar_perception::octomapSrv >
template<>
struct DataType< ::ajgar_perception::octomapSrvResponse>
{
  static const char* value()
  {
    return DataType< ::ajgar_perception::octomapSrv >::value();
  }
  static const char* value(const ::ajgar_perception::octomapSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AJGAR_PERCEPTION_MESSAGE_OCTOMAPSRV_H
