// Generated by gencpp from file ajgar_core/tfValueSrv.msg
// DO NOT EDIT!


#ifndef AJGAR_CORE_MESSAGE_TFVALUESRV_H
#define AJGAR_CORE_MESSAGE_TFVALUESRV_H

#include <ros/service_traits.h>


#include <ajgar_core/tfValueSrvRequest.h>
#include <ajgar_core/tfValueSrvResponse.h>


namespace ajgar_core
{

struct tfValueSrv
{

typedef tfValueSrvRequest Request;
typedef tfValueSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct tfValueSrv
} // namespace ajgar_core


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ajgar_core::tfValueSrv > {
  static const char* value()
  {
    return "e2d3842affcc45c41842273c7f827da7";
  }

  static const char* value(const ::ajgar_core::tfValueSrv&) { return value(); }
};

template<>
struct DataType< ::ajgar_core::tfValueSrv > {
  static const char* value()
  {
    return "ajgar_core/tfValueSrv";
  }

  static const char* value(const ::ajgar_core::tfValueSrv&) { return value(); }
};


// service_traits::MD5Sum< ::ajgar_core::tfValueSrvRequest> should match
// service_traits::MD5Sum< ::ajgar_core::tfValueSrv >
template<>
struct MD5Sum< ::ajgar_core::tfValueSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ajgar_core::tfValueSrv >::value();
  }
  static const char* value(const ::ajgar_core::tfValueSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ajgar_core::tfValueSrvRequest> should match
// service_traits::DataType< ::ajgar_core::tfValueSrv >
template<>
struct DataType< ::ajgar_core::tfValueSrvRequest>
{
  static const char* value()
  {
    return DataType< ::ajgar_core::tfValueSrv >::value();
  }
  static const char* value(const ::ajgar_core::tfValueSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ajgar_core::tfValueSrvResponse> should match
// service_traits::MD5Sum< ::ajgar_core::tfValueSrv >
template<>
struct MD5Sum< ::ajgar_core::tfValueSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ajgar_core::tfValueSrv >::value();
  }
  static const char* value(const ::ajgar_core::tfValueSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ajgar_core::tfValueSrvResponse> should match
// service_traits::DataType< ::ajgar_core::tfValueSrv >
template<>
struct DataType< ::ajgar_core::tfValueSrvResponse>
{
  static const char* value()
  {
    return DataType< ::ajgar_core::tfValueSrv >::value();
  }
  static const char* value(const ::ajgar_core::tfValueSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AJGAR_CORE_MESSAGE_TFVALUESRV_H
