controller_list:
  - name: robot_arm_controller 
    action_ns: follow_joint_trajectory 
    type: FollowJointTrajectory
    default: true 
    joints:
    - base_joint
    - shoulder_joint
    - forearm_joint
    - elbow_joint
  - name: hand_ee_controller 
    action_ns:  follow_joint_trajectory
    type: FollowJointTrajectory
    joints: 
    - suction_joint
   
 
