// Generated by gencpp from file plugin_pneumatic_gripper/Attach.msg
// DO NOT EDIT!


#ifndef PLUGIN_PNEUMATIC_GRIPPER_MESSAGE_ATTACH_H
#define PLUGIN_PNEUMATIC_GRIPPER_MESSAGE_ATTACH_H

#include <ros/service_traits.h>


#include <plugin_pneumatic_gripper/AttachRequest.h>
#include <plugin_pneumatic_gripper/AttachResponse.h>


namespace plugin_pneumatic_gripper
{

struct Attach
{

typedef AttachRequest Request;
typedef AttachResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Attach
} // namespace plugin_pneumatic_gripper


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::plugin_pneumatic_gripper::Attach > {
  static const char* value()
  {
    return "c91fb3be70ce66d19130d40294cf4bd5";
  }

  static const char* value(const ::plugin_pneumatic_gripper::Attach&) { return value(); }
};

template<>
struct DataType< ::plugin_pneumatic_gripper::Attach > {
  static const char* value()
  {
    return "plugin_pneumatic_gripper/Attach";
  }

  static const char* value(const ::plugin_pneumatic_gripper::Attach&) { return value(); }
};


// service_traits::MD5Sum< ::plugin_pneumatic_gripper::AttachRequest> should match
// service_traits::MD5Sum< ::plugin_pneumatic_gripper::Attach >
template<>
struct MD5Sum< ::plugin_pneumatic_gripper::AttachRequest>
{
  static const char* value()
  {
    return MD5Sum< ::plugin_pneumatic_gripper::Attach >::value();
  }
  static const char* value(const ::plugin_pneumatic_gripper::AttachRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::plugin_pneumatic_gripper::AttachRequest> should match
// service_traits::DataType< ::plugin_pneumatic_gripper::Attach >
template<>
struct DataType< ::plugin_pneumatic_gripper::AttachRequest>
{
  static const char* value()
  {
    return DataType< ::plugin_pneumatic_gripper::Attach >::value();
  }
  static const char* value(const ::plugin_pneumatic_gripper::AttachRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::plugin_pneumatic_gripper::AttachResponse> should match
// service_traits::MD5Sum< ::plugin_pneumatic_gripper::Attach >
template<>
struct MD5Sum< ::plugin_pneumatic_gripper::AttachResponse>
{
  static const char* value()
  {
    return MD5Sum< ::plugin_pneumatic_gripper::Attach >::value();
  }
  static const char* value(const ::plugin_pneumatic_gripper::AttachResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::plugin_pneumatic_gripper::AttachResponse> should match
// service_traits::DataType< ::plugin_pneumatic_gripper::Attach >
template<>
struct DataType< ::plugin_pneumatic_gripper::AttachResponse>
{
  static const char* value()
  {
    return DataType< ::plugin_pneumatic_gripper::Attach >::value();
  }
  static const char* value(const ::plugin_pneumatic_gripper::AttachResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLUGIN_PNEUMATIC_GRIPPER_MESSAGE_ATTACH_H
