controller_list:
  - name: fake_amr_gp_controller
    type: $(arg fake_execution_type)
    joints:
      - Revolute_21
      - Revolute_22
      - Revolute_23
initial:  # Define initial robot poses per group
  - group: amr_gp
    pose: default